#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail
set -o xtrace

readonly TARGET_HOST=pi@raspberrypi
readonly TARGET_PATH=/home/pi/time-series
readonly TARGET_ARCH=arm-unknown-linux-musleabihf
readonly SOURCE_PATH=./target/${TARGET_ARCH}/release/time-series

cargo build --release --target=${TARGET_ARCH}
rsync ${SOURCE_PATH} ${TARGET_HOST}:${TARGET_PATH}